// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/waldirborbajr/govote/internal/models"

// PageData mirrors the old web.PageData for gradual migration.
type PageData struct {
	Error       string
	Message     string
	CPF         string
	Polls       []models.Poll
	Poll        models.Poll
	Results     []models.ResultAnswer
	WhatsAppURL string
	AdminUser   *models.Admin
	AdminsList  []models.Admin
	CSRFToken   string
}

func Page(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><meta charset=\"utf-8\"><title>Vote API - PoC</title><link href=\"/static/app.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"/static/htmx.min.js\"></script><script>\n\t\t\tfunction formatCPF(input) {\n\t\t\t\tlet v = input.value.replace(/\\D/g, '');\n\t\t\t\tv = v.replace(/(\\d{3})(\\d)/, '$1.$2');\n\t\t\t\tv = v.replace(/(\\d{3})(\\d)/, '$1.$2');\n\t\t\t\tv = v.replace(/(\\d{3})(\\d{1,2})$/, '$1-$2');\n\t\t\t\tinput.value = v.substring(0, 14);\n\t\t\t}\n\t\t\tfunction formatPhone(input) {\n\t\t\t\tlet v = input.value.replace(/\\D/g, '');\n\t\t\t\tif (v.length > 11) v = v.substring(0, 11);\n\t\t\t\tif (v.length <= 10) {\n\t\t\t\t\tv = v.replace(/(\\d{2})(\\d)/, '($1) $2');\n\t\t\t\t\tv = v.replace(/(\\d{4})(\\d)/, '$1-$2');\n\t\t\t\t} else {\n\t\t\t\t\tv = v.replace(/(\\d{2})(\\d{5})(\\d{4})/, '($1) $2-$3');\n\t\t\t\t}\n\t\t\t\tinput.value = v;\n\t\t\t}\n\t\t</script></head><body class=\"bg-base-200 min-h-screen p-4 md:p-8\"><div class=\"max-w-3xl mx-auto bg-base-100 p-8 rounded-3xl shadow-2xl\"><h1 class=\"text-4xl font-bold mb-2 text-center text-primary\">🗳️ Vote API</h1><p class=\"text-center text-base-content/70 mb-10\">Sistema de Votação Simples e Seguro</p><div id=\"app\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Index(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func Index(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><div class=\"card bg-base-200 shadow-xl p-8 hover:shadow-2xl transition-all\"><div class=\"text-center mb-6\"><div class=\"text-5xl mb-4\">🗳️</div><h2 class=\"text-2xl font-bold mb-2\">Votar</h2><p class=\"text-base-content/70\">Participe das enquetes ativas</p></div><button hx-get=\"/ui/voting-flow\" hx-target=\"#app\" class=\"btn btn-primary btn-lg w-full\">Acessar Votação</button></div><div class=\"card bg-base-200 shadow-xl p-8 hover:shadow-2xl transition-all\"><div class=\"text-center mb-6\"><div class=\"text-5xl mb-4\">⚙️</div><h2 class=\"text-2xl font-bold mb-2\">Administração</h2><p class=\"text-base-content/70\">Gerenciar enquetes e resultados</p></div><button hx-get=\"/ui/admin\" hx-target=\"#app\" class=\"btn btn-secondary btn-lg w-full\">Entrar como Administrador</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
